safe: true
destination: ./_site
auto:        true
lsi:         false
port: 4000
highlighter:    Pygments
highlight:
  linenos: true
highlight_options:
  linenos: true
markdown:    kramdown
permalink:   date
redcarpet:
  extensions: [fenced_code_blocks]
  render_options:
  linenos: true
tags:
  highlight:
    linenos: true
incremental: true
